sitename: "Peter Mumford&rsquo;s <span>W</span>ordPress Dev Blog"
slogan: "Problem Solving for Website Owners and Designers"
intro: "&mdash;by a guy who loves WordPress. And I also love <a href='http://jekyllrb.com/'>Jekyll</a>.  This blog is made with Jekyll. Its hosted at my <a href='https://github.com/photocurio/'>Github</a> account."
# markdown: maruku
url: "http://petermumford.net"
permalink: "/:categories/:title.html"
paginate: 9

# for RSS feed generator
name: "Peter Mumford's WordPress Dev Blog"  
description: "Problem Solving for Website Owners and Designers"
author: "Peter Mumford"