sitename: "Peter Mumford&rsquo;s WordPress Dev Blog"
slogan: "Problem Solving for Website Owners and Designers&nbsp; <i class='fa fa-umbrella fa-lg'></i>"
markdown: redcarpet
url: "http://petermumford.net"
permalink: "/:categories/:title.html"
paginate: 6
